# Generated by Django 6.0.7 on 2026-07-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
        migrations.RenameField(
            model_name='sitesetup',
            old_name='text',
            new_name='title',
        ),
    ]
